version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /loggedin
  script: drivefast.app
  login: required

- url: /index.html
  static_files: index.html 
  upload: index.html

- url: /.*
  script: drivefast.app
  login: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
